name: Build  and publish multi-arch docker images
on:
  push:
    branches:
      - main

env:
  DOCKER_USER: adysh97
  IMG: adysh97/hard_image
  ARCH: linux/ppc64le,linux/amd64

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build multi-arch docker image
        run: |
          docker buildx build  --load --platform linux/amd64 -t $IMG:amd64 .
          docker buildx build --load --platform linux/ppc64le -t $IMG:ppc64le .

      - name: list and inspect
        if: github.event_name == 'push'
        run: |
          docker images | head
          docker inspect $IMG:amd64 | grep arch -i 
          docker inspect $IMG:ppc64le | grep arch -i
