name: Build  and publish multi-arch docker images using native  hardware
on:
  push:
    branches:
      - main

env:
  DOCKER_USER: adysh97
  PPC64LE_VM_IP: ${{ secrets.PPC64LE_VM_IP }}
  VM_IP: ${{ secrets.VM_IP }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
  IMG: adysh97/native_built_image
  ARCH: linux/ppc64le,linux/amd64

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: configure ssh
        run: |
          ssh-keygen -t rsa -q -f "$HOME/.ssh/id_rsa" -N ""
          printenv  SSH_PRIVATE_KEY > ~/.ssh/id_rsa
          ssh-keyscan -H $VM_IP >~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add 
          ssh -T $PPC64LE_VM_IP grep name -i /etc/os-release
          ssh -T $PPC64LE_VM_IP arch

      - name: add native builder
        run: |
          eval $(ssh-agent)
          ssh-add 
          docker context create linux-ppc64le-context  --docker "host=ssh://$PPC64LE_VM_IP"
          #docker context use linux-ppc64le-context 
          #docker images
          docker buildx create --name amd64-ppc64le-builder  --platform $ARCH  linux-ppc64le-context
          docker buildx use amd64-ppc64le-builder
          docker buildx inspect amd64-ppc64le-builder

      - name: Build multi-arch docker image
        run: |
          eval $(ssh-agent)
          ssh-add 
          docker buildx ls
          docker buildx build  --load --platform linux/amd64 -t $IMG:amd64 .
          docker buildx build --load --platform linux/ppc64le -t $IMG:ppc64le .
          docker buildx build --load --platform linux/arm64 -t $IMG:arm64 .

      - name: list and inspect
        if: github.event_name == 'push'
        run: |
          docker images | head
          docker inspect $IMG:amd64 | grep arch -i 
          docker inspect $IMG:ppc64le | grep arch -i
          docker inspect $IMG:arm64 | grep arch -i
